FROM golang:1.22-alpine AS builder

WORDIR /app

COPY go.mod go.sum .

RUN go.mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/server

FROM alpine:latest

RUN apk update && apk add --no-cache ca-certificates ffmpeg lib6c6-compat

WORKDIR /root/

COPY --from=builder /app/myapp .